version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # postgres image expects POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    # Optionally you can mount the code for local development
    volumes:
      - .:/app:rw

volumes:
  db_data:
